{% set name = "stockwell" %}
{% set version = "1.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/stockwell-{{ version }}.tar.gz
  sha256: 48b1df34fb27bb110650823c2a9f2b4e2a6a7412f3c1c7b05d69419552a26ea8

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - numpy
    - pip
    - python
    - fftw
  run:
    - python
    - fftw

test:
  imports:
    - stockwell
  commands:
    - pip check
  requires:
    - pip
    - pytest
  commands:
    - pytest --pyargs stockwell

about:
  home: https://github.com/claudiodsf/stockwell
  summary: Time-frequency analysis through Stockwell transform
  license: GPL-3.0-or-later
  license_file: LICENSE.txt
  description: |
    Python package for time-frequency analysis through Stockwell transform.
    Based on original code from NIMH MEG Core Facility
    (https://kurage.nimh.nih.gov/meglab/Meg/Stockwell).
  dev_url: https://github.com/claudiodsf/stockwell

extra:
  recipe-maintainers:
    - claudiodsf
